### ISSUE TITLE
Upgrading Node to `8.9.4` and/or upgrading the `yarn` version in the image

### ISSUE THREAD

**Issue by kiriappeee** [bufferapp/buffer-publish#262]
### Summary
Upgrade the app from `8.1.2` to use Node `8.9.4` to keep it updated with the current LTS of Node. This includes a few important security updates as well.

**More importantly**: Upgrade our version of `yarn`. The current version that comes in `node:8.1.2-slim/alpine` is `0.24`. This does NOT have access to `yarn workspaces` which were enabled from version `0.27` onwards only. This means that the build step of `yarn install` in [our Dockerfile](https://github.com/bufferapp/buffer-publish/blob/master/Dockerfile#L9) might actually be behaving very differently from the way we are currently expecting it to. Upgrading the image we use to `node:8.9.4` automatically gives us an updated version of `yarn`.

### Context

There's a little bit to unpack here regarding `yarn`. I read through the `yarn` and `lerna` docs to understand how the workspaces work. Some important points:

* `lerna` gave a much better way to manage the idea of workspaces first
* `yarn` supported workspaces from version `0.27` onwards. At the time it needed a flag in a `.yarnrc` file to be enabled. It is now enabled by specifying in the `package.json` file.
* `lerna` then supported `yarn workspaces` from version `2` upwards which `publish` takes advantage of[1](https://github.com/bufferapp/buffer-publish/blob/master/package.json#L103-L105), [2](https://github.com/bufferapp/buffer-publish/blob/master/lerna.json#L6-L7). 
  * The above specification means that there is _no difference_ between running `lerna bootstrap` and `yarn` or `yarn install`. With the above specification `lerna bootstrap` becomes an alias for `yarn install` as specified by lerna/lerna#899
* If we run `docker run --rm -v $(pwd):/src -w /src node:8.1.2-slim yarn install` inside of `buffer-publish` directory we'll notice two things:
  * Not all the modules are installed
  * `yarn.lock` is modified. We don't know how much a difference there is between the two `yarn` version algorithms. 

### Concerns

This is a pretty big jump in Node versions. We would need to test this a bit and profile things ideally to ensure no regressions occur. 

If we aren't quite ready to upgrade to 8.9.4, then I could help open a PR which has either:

* New build steps in Docker to ensure that a newer version of `yarn` is installed OR
* A new `bufferapp/node:publish` (or something similar) image that has the intended `yarn` version (`1.x.x`) installed.

### PS - Edit

In case anyone wonders how it's been working so far (I was certainly scratching my head about that), it's because of the `pre-build.sh` file. _edit for clarity_

* `pre-build.sh` runs `yarn && yarn run bootstrap` which runs `lerna bootstrap` using node 8.9.4 and yarn 1.3.2
* This installs all the necessary packages in a correct workspaced manner into `node_modules`
* `node_modules` then gets mounted at the `docker build` step
* We run `yarn install` inside of the `Dockerfile` but that doesn't really have an effect or it might be silently having an effect we don't know about since node_modules is already prepared. Either way, thanks to the effect of `pre-build.sh`, all the necessary packages are installed correctly.

**Comment by hamstu** [comment]
Late here @kiriappeee, so sorry!

I'm all for doing this. (Is it already done, now?) I think moving into LTS releases is a smart strategy. I would be very surprised to see any kind of regression or errors from this.
