### ISSUE TITLE
buffer-dev 404

### ISSUE THREAD

**Issue by jlangevin** [bufferapp/buffer-publish#273]
I was hoping to set up a dev environment and play with the new publish app.  However, I'm getting a 404 on the link to buffer-dev in the first step below.  Various Googling for buffer-dev isn't turning up anything either and the npm page for buffer-publish points to the same 404 url.  Perhaps it was taken down or I should be looking somewhere else?  Any help/insight is much appreciated!

1. Get your buffer-dev environment setup → https://github.com/bufferapp/buffer-dev

**Comment by hamstu** [comment]
Thanks for reaching out @jlangevin! Check out my response in this issue 👉 #276 😄
