### ISSUE TITLE
Broken link for buffer-dev

### ISSUE THREAD

**Issue by muratdogan17** [bufferapp/buffer-publish#276]
In readme file it says its required to get buffer dev environment but its link is broken : https://github.com/bufferapp/buffer-dev

**Comment by hamstu** [comment]
@muratdogan17 Out of curiosity, was there something specific you were looking to change or work on? 😄

**Comment by muratdogan17** [comment]
@hamstu nope, I just want to discover your codebase, conventions etc. Because I've applied for front end developer role and want to discover before interviews :)

**Comment by hamstu** [comment]
@muratdogan17 Gotcha! 👍 Great idea. Hopefully you can at least scan through the codebase to get an idea of how we're building things. Like I said I would love to make running/contributing possible in the future, so stay tuned.

**Comment by jlangevin** [comment]
Thanks for the info @hamstu.  Like muratdogan17, I've been looking through your code base.  While I haven't applied for any of your positions (perhaps not at the level of your front end dev openings at the moment), I found you on github after coming across your job listings.  I've been looking through buffer-publish and several of your other repos to gain insight on how to better structure my react code as it grows.  I was also looking to see the end-to-end api interactions in action, but not the end of the world.  Have a good one!
