### ISSUE TITLE
Use common jest config file

### ISSUE THREAD

**Issue by djfarrelly** [bufferapp/buffer-publish#3]
### Idea
Can we create a single jest config file with "good defaults" in the root of this repo to reduce the need from copying the jest config into each package? 

[Example package.json](https://github.com/bufferapp/buffer-publish/blob/9b2031784a89ff0253103189b76d85445e8b0e57/packages/example/package.json#L13-L26)
Jest documentation: https://facebook.github.io/jest/docs/configuration.html

---
Created this to not forget this one from our convo yesterday @hharnisc 😄

**Comment by hamstu** [comment]
Closing since this is done! 👌
